language: ruby
branches:
  only:
  - master
before_install:
- gem install sass
script:
- bundle exec jekyll build
- bundle exec rake travis
env:
	secure: "UX9zPw/PbCvYgfOCGnTb8ijmpaB/V3wziMzfhh9bS+48Yzupl8msdEMtFNz3FV6RRDpjq4Ke6ObhBtZUM1HzWKE5p73eFw1771MtKlhtwPeMfo8tkrQxD7GSvvYicmc6wB38FoCV9mPBJvJQ+GKvSN8qyVCv25oTCtbgPoHt4FY="
