language: ruby
branches:
  only:
  - master
before_install:
  - gem install sass
script:
  - "bundle exec jekyll build"
  - ./build.sh
env:
  secure: "Tq6HPCRGuAJO//VCBUF+LFJzMo/jq0tWDJ0nEPSOQZ2xdr8ZdBUCwLcHe/+DD6tSyjFkOVe9R31tNrTjPdxXtRbDZqQSbFnC6+g5mjAEZcDbOxjdf5LbSHhT3lqseJujbr7gtApr8i97X9LxYunegzy5vH0h0hE9nvasLVh2pL0="