language: ruby
branches:
  only:
  - master
before_install:
- gem install sass
script:
- bundle exec jekyll build
- "./build.sh"
global:
  env:
    secure: lAboHR0Rnyv2eSQPbmhqfAYW9yX/55ByXSv/9r9g0bWZLeIUYrvbNltHB72TwpICfLIFZKvr3EVfcFl0DXjF+vbgZc4P/5TpbstkjybYHBBu3p2ZCTWLGvPWrI5kK6FJzCjDbTJoS21t7qp0ITmbLFc+WkJVbtRbObCua65gVZg=
