# Site settings
baseurl: /prose-docs
github_username:  slwen

org_name: slwen
repo_name: prose-docs
prose_branch: master

sass:
  sass_dir: /style/
  style: :compressed

# Build settings
markdown: kramdown