# Site settings
baseurl: /prose-docs
github_username:  slwen

org_name: slwen
repo_name: prose-docs
prose_branch: master

sass:
  sass_dir: /style/
  style: :compressed

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data","tables","prettify","smartypants"]